version: 0.2
phases:

  install:
    commands:
      - echo "=== OS Info ==="
      - uname -a
      - cat /etc/os-release
      - echo "=== Installing yum-utils ==="
      - yum install -y yum-utils
      - echo "=== Adding HashiCorp Repo ==="
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - echo "=== Installing Terraform ==="
      - yum install -y terraform
      - echo "=== Verifying Terraform Installation ==="
      - which terraform
      - terraform --version

  pre_build:
    commands:
      - echo "=== Running terraform init ==="
      - terraform init
      - terraform validate
  
  build:
    commands:
      - ls -l
      - cat terraform.tfvars
      - terraform apply -var-file="terraform.tfvars" --auto-approve