version: 0.2
phases:

  install:
    commands:
      - echo "=== OS Info ==="
      - uname -a
      - cat /etc/os-release
      - echo "=== Installing yum-utils ==="
      - yum install -y yum-utils
      - echo "=== Adding HashiCorp Repo ==="
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - echo "=== Installing Terraform ==="
      - yum install -y terraform
      - echo "=== Verifying Terraform Installation ==="
      - which terraform
      - terraform --version

  pre_build:
    commands:
      - echo "=== Running terraform init ==="
      - terraform init
      - terraform validate
  
  build:
    commands:
      - echo "<html><body>Test Page</body></html>" > src/test.html
      - terraform apply --auto-approve
      - ls -R src

  post_build:
    commands:
      - echo "=== Verifying Files Before Artifact Upload ==="
      - ls -R src

artifacts:
  base-directory: src
  files:
    - '**/*.html'
  discard-paths: yes
