version: 0.2
phases:

  install:
    commands:
      - echo "=== OS Info ==="
      - uname -a
      - cat /etc/os-release
      - echo "=== Installing yum-utils ==="
      - yum install -y yum-utils
      - echo "=== Adding HashiCorp Repo ==="
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - echo "=== Installing Terraform ==="
      - yum install -y terraform
      - echo "=== Verifying Terraform Installation ==="
      - which terraform
      - terraform --version

  pre_build:
    commands:
      - echo "=== Current Working Directory ==="
      - pwd
      - echo "=== Files ==="
      - ls -la
      - echo "=== Running terraform init ==="
      - terraform init
      - terraform validate
  
  build:
    commands:
      - echo "Cleaning up non-HTML files..."
      - find src -type f ! -name "*.html" -delete
      - terraform plan

  artifacts:
    files:
      - '**/*.html'
    discard-paths: yes