version: 0.2
phases:

  install:
    commands:
      # Install HashiCorp's GPG key and repository for Amazon Linux
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      # Install Terraform
      - yum install -y terraform
      # Verify installation
      - terraform --version

  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform plan